active: 0
active_methods: []
autofocus_num: 0
autofocus_samples: 15
autofocus_stepsize: 25
copy_path: ''
duration: 75
expt_last_image: C:\Users\rene\Documents\Programming\PPS-app\software\data\2018-12-10\expt_010\2018-12-10_Bright_0.jpg
i2c_send_delay: 0.05
image_set_num: 1
images_left: 7
images_taken: 3
images_total: 10
imaging_method: Custom
imaging_num: 0
interval: 8
interval_autofocus: 3600.0
is_autofocus: false
is_autofocus_busy: false
is_autofocus_request: false
last_expt_date: '20190816'
last_expt_num: 16
path_last_expt: C:\Users\renelachmann\Documents\Programming\UC2_Software-GIT\GUI\RASPIapp\data\20190816\expt_001
snap_num: 0
success: false
time_left: 53
time_passed: 22
