NA: 1
color:
- 255
- 255
- 255
color_picked:
- 255
- 255
- 255
color_picker_counter: 0
default:
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
intensity: 75
intensity_expt: 120
matrixdim:
- 8
- 8
picked:
- 255
- 255
- 255
update_fluoled_active: false
update_matrix_active: false
user:
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
