active: 0
active_camProp: null
active_methods: []
autofocus_busy: false
autofocus_new: true
autofocus_now: false
autofocus_num: 1
autofocus_samples: 15
autofocus_stepsize: 25
copy_path: ''
duration: 45
expt_last_image: /home/uc2/UC2/UC2-GUI/data/20200716/expt_006/20200716-MEAS-Custom--0.jpg
fluo_bayer_explizit: true
i2c_send_delay: 0.05
image_set_num: 1
images_left: 8
images_taken: 2
images_total: 10
imaging_active: false
imaging_cause: MEAS
imaging_method: Custom
imaging_method_dic:
  Bright: btn_imaging_technique_1
  Custom: btn_imaging_technique_3
  Ext: btn_imaging_technique_6
  FPM: btn_imaging_technique_4
  Fluor: btn_imaging_technique_5
  qDPC: btn_imaging_technique_2
imaging_num: 1
interval: 5
is_autofocus: false
last_expt_date: '20200716'
last_expt_num: 6
path_last_expt: /home/uc2/UC2/UC2-GUI/data/20200716/expt_006
snap_num: 2
success: false
take_raw: 1
time_left: 44
time_passed: 1
tomo_active: false
