NA: 1
color:
- 255
- 255
- 255
color_picked:
- 255
- 255
- 255
color_picker_counter: 4
default:
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
intensity: 86
intensity_expt: 86
matrixdim:
- 8
- 8
picked:
- 255
- 255
- 255
update_fluoled_active: false
update_matrix_active: false
user:
- - &id001
    - 0
    - 0
    - 0
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
- - &id002
    - 0
    - 0
    - 0
  - *id002
  - - 0
    - 0
    - 0
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
- - &id003
    - 0
    - 0
    - 0
  - *id003
  - *id003
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - *id003
  - *id003
  - *id003
- - &id004
    - 0
    - 0
    - 0
  - *id004
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - - 0
    - 0
    - 0
  - *id004
  - *id004
  - *id004
- - &id005
    - 0
    - 0
    - 0
  - *id005
  - *id005
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - *id005
  - *id005
  - *id005
- - &id006
    - 0
    - 0
    - 0
  - *id006
  - *id006
  - - 0
    - 0
    - 0
  - *id006
  - *id006
  - *id006
  - *id006
- - &id007
    - 0
    - 0
    - 0
  - *id007
  - *id007
  - *id007
  - *id007
  - *id007
  - *id007
  - *id007
- - &id008
    - 0
    - 0
    - 0
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
