backlash: 10
bayer_explizit: true
direction: 1
done: true
motor: DRVX
posEND: 10465
posSTART: 10259
step_number: 6
steps: 3
stepsize: 68
steptime: 0.2
steptime_active: 0
take_image: true
total_dist: 206
totaltime: 5
